#!/bin/bash

## Author: Qi Yu
## Contact: dryuqi@gmail.com

Soft="juicer_wrap"
#VERSION="1.0.0"

function usage {
	echo -e "usage : $Soft -i1 FASTQ -i2 FASTQ -b BAM -g GENOME -en ENZYME -o OUTPUT_name"
}

function help {
    usage;
    echo 
    echo "$Soft"
    echo "---------------"
    echo "OPTIONS"
    echo
    echo "   -i1 FASTQ : input _R1.fastq or fastq.gz file"
    echo "   -i2 FASTQ : input _R2.fastq or fastq.gz file"
    echo "   -b BAM : input BAM file"
    echo "   -o OUTPUT : physical path you want output locate, where to generate align folder"
    echo "   -g GENOME : genome mm10 or hg19"
    echo "   -en : digest enzyme for Hi-C MboI or HinIII"
    echo "   [-p] : if specified run $Soft on a cluster"
    echo "   [-h]: help"
   # echo "   [-v|--version]: version"
    exit;
}

function opts_error {
    echo -e "Error : invalid parameters !" >&2
    echo -e "Use $Soft -h for help"
    exit
}

if [ $# -lt 1 ]
then
    usage
    exit
fi


CLUSTER=0
MAKE_OPTS=""
INPUT1=""
INPUT2=""
INPUTBAM=""
OUTPUT=""
ENZYME=""
GENOME=""


while getopts ":i1:i2:b:o:en:g:s;ph" OPT
do
    case $OPT in
	i1) INPUT1=$OPTARG;;
	i2) INPUT2=$OPTARG;;
	b) INPUTBAM=$OPTARG;;
	o) OUTPUT=$OPTARG;;
	en) ENZYME=$OPTARG;;
	g) GENOME=$OPTARG;;
	s) MAKE_OPTS="$MAKE_OPTS $OPTARG";;
	p) CLUSTER=1 ;;
	h) help ;;
	\?)
	     echo "Invalid option: -$OPTARG" >&2
	     usage
	     exit 1
	     ;;
	 :)
	     echo "Option -$OPTARG requires an argument." >&2
	     usage
	     exit 1
	     ;;
    esac
done

if [[ -z $INPUT1 || -z $INPUT2 || -z $INPUTBAM || -z $OUTPUT || -z $ENZYME || -g $GENOME ]]; then
    usage
    exit
fi

###################################
#check
##################################

if [ ! -e $INPUT1 ]; then
    echo "Inputs '$INPUT1' not found. Exit."
    exit -1
fi
if [ ! -e $INPUT2 ]; then
    echo "Inputs '$INPUT2' not found. Exit."
    exit -1
fi
if [ ! -e $INPUTBAM ]; then
    echo "Inputs '$INPUTBAM' not found. Exit."
    exit -1
fi

##############################
#clean
###################################
cd $OUTPUT 
module load juicer;
#genom=$2
#enzyme=$3
#fastq=$1
#sampleid=$4
rm -r splits debug fastq
mv aligned aligned_old

nbin1=$(find -L $INPUT1 -name "*.fastq" -o -name "*.fastq.gz" | wc -l)
nbin2=$(find -L $INPUT2 -name "*.fastq" -o -name "*.fastq.gz" | wc -l)

if [ $nbin1 == 0 ]; then
	die "Error: Directory Hierarchy of rawdata '$INPUT1' is not correct. No '.fastq(.gz)' files detected"
fi

if [ $nbin2 == 0 ]; then
        die "Error: Directory Hierarchy of rawdata '$INPUT2' is not correct. No '.fastq(.gz)' files detected"
fi


mkdir fastq; cd fastq; ln -s ../$INPUT2 .; ln -s ../$INPUT1 . 

#This program has been only tested for juicer 1.5 edited by Qi and run at biowulf, please edited accordingly

/data/yuq3/HiC/juicer/scripts/juicer.sh -g $genom -z /data/yuq3/HiC/juicer/references/${genom}.fa -p /data/yuq3/HiC/juicer/references/${genom}.chrom.sizes -q norm -d $OUTPUT -D /data/yuq3/HiC/juicer/ -s $enzyme

#################################################


